import Head from 'next/head'
import Header from '@/components/Header'
import Technologies from '@/components/Technologies'
import Creator from '@/components/Creator'
import Footer from '@/components/Footer'
import Image from 'next/image'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>StrAPI | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main 
        className=' flex flex-col items-center min-h-screen w-full bg-gradient-to-b from-darkblue via-darkblue to-black text-gray-200 p-3 relative'
      >
        <Header />
        <div className='w-full max-w-screen-2xl mt-14 flex flex-col items-center'>
            
          <h1 className='mb-32 text-5xl text-center'>Welcome to Str<span className=' text-amber-600'>API</span>!</h1>

          <div className='relative flex justify-center items-center'>
            <div className='absolute inset-0 bg-amber-600 rounded-full blur-2xl'></div>
            <Image 
              src='/logo.png' 
              alt='hero image' 
              height={350} 
              width={350} 
              className='m-10 relative z-10 bg-gradient-to-b from-darkblue via-sky-950 to-darkblue  rounded-full' 
            />
          </div>

          <h2 className='text-center m-8 mt-32 text-3xl text-transparent bg-clip-text bg-gradient-to-r from-sky-500 to-amber-600'>
            Stress-test your application to de-stress your occupation.
          </h2>

          <Link 
            href="https://github.com/oslabs-beta/strapi"
            target="_blank"
            className='text-2xl rounded-md p-4 mt-8 bg-gradient-to-r from-darkblue via-sky-950 to-darkblue shadow-md shadow-slate-600 hover:scale-105 hover:text-sky-300 transition-all'
          >
            Click Here To Get Started
          </Link>

          <hr className=' border-sky-800 w-5/6 m-24' />

          <h1 className='text-center col-span-3 text-3xl m-6 mb-8'>
            About Str
            <span className=' text-amber-600'>
              API
            </span>
            :
          </h1>

          <section className='flex flex-wrap justify-center items-center mb-8 gap-8 p-5 '>
            <p 
              className='text-center rounded-lg shadow-md shadow-slate-600 text-xl w-1/4 min-w-250 h-56 flex justify-center items-center bg-gradient-to-r from-darkblue via-sky-950 to-darkblue p-4'
            >
              StrAPI is designed to be a free and open-source alternative to stress-test your API routes.
            </p>
            <p 
              className='text-center rounded-lg shadow-md shadow-slate-600 text-xl w-1/4 min-w-250 h-56 flex justify-center items-center bg-gradient-to-r from-darkblue via-sky-950 to-darkblue p-4'
            >
              To install StrAPI, check out our GitHub repo linked at the top of the page, and follow the instructions in the README.
            </p>
            <p 
              className='text-center rounded-lg shadow-md shadow-slate-600 text-xl w-1/4 min-w-250 h-56 flex justify-center items-center bg-gradient-to-r from-darkblue via-sky-950 to-darkblue p-4'
            >
              Stress-test your API routes and view the latency distribution of your tests!
            </p>
          </section>

          <hr className=' border-sky-800 w-5/6 m-24' />

          <h1 
            className='flex justify-center items-center m-8 text-3xl text-transparent bg-clip-text bg-gradient-to-r from-sky-500 to-amber-600'
          >
            Technologies:
          </h1>
            
          <Technologies />


          <hr className=' border-sky-800 w-5/6 m-24' />

          <section className='flex flex-col items-center'>
            <h1 className='text-3xl mb-6'>Str<span className=' text-amber-600'>API</span> in the Media:</h1>

            <p className='flex justify-center items-center text-lg'>Check out our article on &nbsp;
              <Link href="/" className='text-transparent bg-clip-text bg-gradient-to-r from-sky-500 to-amber-600 flex justify-center items-center hover:scale-110 transition-all'>
                Medium!
              </Link>
            </p>

          </section>

          <hr className=' border-sky-800 w-5/6 m-24' />

          <h1 
            className='m-8 text-3xl text-transparent bg-clip-text bg-gradient-to-r from-sky-500 to-amber-600'
          >
            Meet The Creators:
          </h1>

          <section className='flex flex-wrap justify-center w-full p-5 gap-3 '>
            <Creator 
              name='Steven Min' 
              linkedin='https://www.linkedin.com/in/steven-min/' 
              github='https://github.com/choopi-js' 
            />
            <Creator 
              name='Zachary Skobkariov' 
              linkedin='https://www.linkedin.com/in/zachary-skobkariov/' 
              github='https://github.com/CubeLightning' />
            <Creator 
              name='Jennifer Liu' 
              linkedin='https://www.linkedin.com/in/jennliu3/' 
              github='https://github.com/jennlee3' 
            />
            <Creator 
              name='Jack Moorman' 
              linkedin='https://www.linkedin.com/in/jack-moorman' 
              github='https://github.com/jackmoorman' 
            />
            <Creator 
              name='Mauricio Garza' 
              linkedin='https://www.linkedin.com/in/mauricio-garza-guzman/' 
              github='https://github.com/mauiwowie88' 
            />
          </section>

        </div>
        <Footer />
      </main>
    </>
  )
}
